//
//  OFMethods.swift
//  OpenfortSwift
//
//  Created by Pavel Gurkovskii on 2025-07-16.
//

public enum OFMethods {
    public static let addEmail = "addEmail"
    public static let authenticateWithSIWE = "authenticateWithSIWE"
    public static let configure = "configure"
    public static let create = "create"
    public static let exportPrivateKey = "exportPrivateKey"
    public static let get = "get"
    public static let getAccessToken = "getAccessToken"
    public static let getEmbeddedState = "getEmbeddedState"
    public static let getEthereumProvider = "getEthereumProvider"
    public static let getURL = "getURL"
    public static let getUserInstance = "getUserInstance"
    public static let initLinkOAuth = "initLinkOAuth"
    public static let initLinkSiwe = "initLinkSiwe"
    public static let initOAuth = "initOAuth"
    public static let initSIWE = "initSIWE"
    public static let linkPhoneOtp = "linkPhoneOtp"
    public static let linkWallet = "linkWallet"
    public static let linkWithSiwe = "linkWithSiwe"
    public static let list = "list"
    public static let logInWithEmailOtp = "logInWithEmailOtp"
    public static let logInWithPhoneOtp = "logInWithPhoneOtp"
    public static let logInWithEmailPassword = "logInWithEmailPassword"
    public static let loginWithIdToken = "loginWithIdToken"
    public static let loginWithSiwe = "loginWithSiwe"
    public static let logOut = "logout"
    public static let poolOAuth = "poolOAuth"
    public static let ping = "ping"
    public static let recover = "recover"
    public static let requestEmailOtp = "requestEmailOtp"
    public static let requestEmailVerification = "requestEmailVerification"
    public static let requestPhoneOtp = "requestPhoneOtp"
    public static let requestResetPassword = "requestResetPassword"
    public static let resetPassword = "resetPassword"
    public static let sendSignatureSessionRequest = "sendSignatureSessionRequest"
    public static let sendSignatureTransactionIntentRequest = "sendSignatureTransactionIntentRequest"
    public static let signMessage = "signMessage"
    public static let signTypedData = "signTypedData"
    public static let signUpGuest = "signUpGuest"
    public static let signUpWithEmailPassword = "signUpWithEmailPassword"
    public static let storeCredentials = "storeCredentials"
    public static let unlinkOAuth = "unlinkOAuth"
    public static let unlinkWallet = "unlinkWallet"
    public static let validateAndRefreshToken = "validateAndRefreshToken"
    public static let verifyEmail = "verifyEmail"
    public static let verifyEmailOtp = "verifyEmailOtp"
    public static let setRecoveryMethod = "setRecoveryMethod"
}
